# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Train_R <- function(x) {
    .Call('deepboost_Train_R', PACKAGE = 'deepboost', x)
}

Predict_R <- function(x) {
    .Call('deepboost_Predict_R', PACKAGE = 'deepboost', x)
}

Evaluate_R <- function(x) {
    .Call('deepboost_Evaluate_R', PACKAGE = 'deepboost', x)
}

