# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Train_R <- function(data, tree_depth, num_iter, beta, lambda, loss_type, verbose) {
    .Call('deepboost_Train_R', PACKAGE = 'deepboost', data, tree_depth, num_iter, beta, lambda, loss_type, verbose)
}

Predict_R <- function(newdata, model) {
    .Call('deepboost_Predict_R', PACKAGE = 'deepboost', newdata, model)
}

Evaluate_R <- function(data, model) {
    .Call('deepboost_Evaluate_R', PACKAGE = 'deepboost', data, model)
}

